In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv(r"D:\Study\SEM-IX\ML\Practical\Internal\Files\winequality-white.csv",";")
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [2]:
#data[Feature].replace(('Yes','No'),(1,0),inplace=True)
X = data.iloc[:,[0,11]].values
y = data.iloc[:,11].values

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [5]:
X_train

array([[6.5, 6. ],
       [8. , 6. ],
       [5.6, 6. ],
       ...,
       [8.2, 6. ],
       [6.5, 7. ],
       [7.1, 7. ]])

In [6]:
X_train = scaler.transform(X_train)
x_test = scaler.transform(X_test)

In [7]:
from sklearn.naive_bayes import GaussianNB

In [8]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [9]:
y_pred = model.predict(X_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        36
           5       0.00      0.00      0.00       303
           6       0.00      0.00      0.00       428
           7       0.00      0.00      0.00       180
           8       0.00      0.00      0.00        29
           9       0.00      1.00      0.00         1

    accuracy                           0.00       980
   macro avg       0.00      0.14      0.00       980
weighted avg       0.00      0.00      0.00       980

[[  0   0   0   0   0   0   3]
 [  0   0   0   0   0   0  36]
 [  0   0   0   0   0   0 303]
 [  0   0   0   0   0   0 428]
 [  0   0   0   0   0   0 180]
 [  0   0   0   0   0   0  29]
 [  0   0   0   0   0   0   1]]


D:\Software\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
#from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [14]:
print('Accuracy of Naive_Bayes model on training set: {:.2f}'.format(model.score(X_train,y_train)*100))
print('Accuracy of Naive_Bayes model on test set: {:.2f}'.format(model.score(X_test,y_test)*100))

Accuracy of Naive_Bayes model on training set: 100.00
Accuracy of Naive_Bayes model on test set: 0.10
